#!/bin/sh
result=$(python <<EOF
from notebook.services.config.manager import ConfigManager
cm = ConfigManager()
cm.update('cite2c', {'zotero':{"user_id": "5043554","username": "econ-ark","access_token": "XZpH9NsoAZmDMmjLKiy8xMXX"}})
EOF
)
